import streamlit as st
import plotly.express as px
from utils import load_data, apply_custom_css

# --- PAGE CONFIG ---
st.set_page_config(
    page_title="Historical Analytics",
    page_icon="🕰️",
    layout="wide",
)

apply_custom_css()

# --- HEADER ---
st.title("🕰️ Wikipedia Historical Analytics")
st.caption("Deep dive into batch-processed historical data (generated by Spark)")
st.divider()

# --- 1. OVERVIEW TRENDS ---
st.subheader("Last 7 Days Trends")
trends_df = load_data("SELECT * FROM historical_daily_trends ORDER BY date")

if not trends_df.empty:
    col1, col2 = st.columns(2)
    with col1:
        fig_events = px.line(
            trends_df, x="date", y=["total_events", "events_7day_avg"],
            title="Daily Events & Trend", template="plotly_dark",
            labels={"value": "Count", "variable": "Metric"}
        )
        st.plotly_chart(fig_events, use_container_width=True)
    
    with col2:
        fig_bytes = px.bar(
            trends_df, x="date", y="total_bytes",
            title="Daily Volume (Bytes)", template="plotly_dark"
        )
        st.plotly_chart(fig_bytes, use_container_width=True)
else:
    st.info("No historical trends data available yet.")


# --- 2. HOURLY PATTERNS ---
st.subheader("Hourly Activity Patterns (GMT)")
hourly_df = load_data("SELECT * FROM historical_hourly_patterns ORDER BY hour_of_day")

if not hourly_df.empty:
    fig_hourly = px.bar(
        hourly_df, x="hour_of_day", y=["human_events", "bot_events"],
        title="Edit Activity by Hour of Day",
        template="plotly_dark",
        barmode="stack"
    )
    st.plotly_chart(fig_hourly, use_container_width=True)
else:
    st.info("No hourly pattern data available yet.")


# --- 3. LANGUAGE & SERVER DISTRIBUTION ---
col3, col4 = st.columns(2)

with col3:
    st.subheader("Language Distribution")
    lang_df = load_data("SELECT * FROM historical_language_distribution LIMIT 20")
    if not lang_df.empty:
        fig_lang = px.pie(
            lang_df, names="language", values="edit_count",
            title="Edits by Language", hole=0.4, template="plotly_dark"
        )
        st.plotly_chart(fig_lang, use_container_width=True)
    else:
        st.info("No language data available.")

with col4:
    st.subheader("Top Servers")
    server_df = load_data("SELECT * FROM historical_server_rankings ORDER BY rank LIMIT 15")
    if not server_df.empty:
        fig_server = px.bar(
            server_df, x="server_name", y="edit_count",
            color="unique_users",
            title="Most Active Servers",
            template="plotly_dark"
        )
        st.plotly_chart(fig_server, use_container_width=True)
    else:
        st.info("No server ranking data available.")


# --- 4. TOP CONTRIBUTORS ---
st.subheader("Top Contributors Leaderboard")
users_df = load_data("SELECT * FROM historical_top_contributors ORDER BY edit_count DESC LIMIT 50")

if not users_df.empty:
    st.dataframe(
        users_df,
        use_container_width=True,
        hide_index=True,
        column_config={
            "user": "User Name",
            "is_bot": "Is Bot?",
            "edit_count": st.column_config.NumberColumn("Total Edits"),
            "total_bytes": st.column_config.NumberColumn("Total Volume (Bytes)"),
            "pages_created": st.column_config.NumberColumn("New Pages Created"),
        }
    )
else:
    st.info("No contributor data available yet.")
